// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBagZWutsFa2BDW5Vw1phTJnoazrSC14fY',
    appId: '1:681758766010:web:4290373d947318e96e2383',
    messagingSenderId: '681758766010',
    projectId: 'bazar-suez-app',
    authDomain: 'bazar-suez-app.firebaseapp.com',
    databaseURL: 'https://bazar-suez-app-default-rtdb.firebaseio.com',
    storageBucket: 'bazar-suez-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuSD2l5deFdKPfW944a40LlrZvu9Ukm6c',
    appId: '1:681758766010:android:e0ffc0a45fd7f5bc6e2383',
    messagingSenderId: '681758766010',
    projectId: 'bazar-suez-app',
    databaseURL: 'https://bazar-suez-app-default-rtdb.firebaseio.com',
    storageBucket: 'bazar-suez-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgM95OcGbR3lHbtRdOXo4nwazI_5zcuZk',
    appId: '1:681758766010:ios:84a0b105a9c4e5c86e2383',
    messagingSenderId: '681758766010',
    projectId: 'bazar-suez-app',
    databaseURL: 'https://bazar-suez-app-default-rtdb.firebaseio.com',
    storageBucket: 'bazar-suez-app.firebasestorage.app',
    androidClientId: '681758766010-7806phk8rqevggru1fha2vbc1baa67hn.apps.googleusercontent.com',
    iosClientId: '681758766010-o1shplst2omdmk0gr4h3eu2eh4lpq1e3.apps.googleusercontent.com',
    iosBundleId: 'com.example.suezAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgM95OcGbR3lHbtRdOXo4nwazI_5zcuZk',
    appId: '1:681758766010:ios:84a0b105a9c4e5c86e2383',
    messagingSenderId: '681758766010',
    projectId: 'bazar-suez-app',
    databaseURL: 'https://bazar-suez-app-default-rtdb.firebaseio.com',
    storageBucket: 'bazar-suez-app.firebasestorage.app',
    androidClientId: '681758766010-7806phk8rqevggru1fha2vbc1baa67hn.apps.googleusercontent.com',
    iosClientId: '681758766010-o1shplst2omdmk0gr4h3eu2eh4lpq1e3.apps.googleusercontent.com',
    iosBundleId: 'com.example.suezAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBagZWutsFa2BDW5Vw1phTJnoazrSC14fY',
    appId: '1:681758766010:web:63fb3d33f56a23fa6e2383',
    messagingSenderId: '681758766010',
    projectId: 'bazar-suez-app',
    authDomain: 'bazar-suez-app.firebaseapp.com',
    databaseURL: 'https://bazar-suez-app-default-rtdb.firebaseio.com',
    storageBucket: 'bazar-suez-app.firebasestorage.app',
  );
}
